name: cd

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]


  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::647932856976:role/GithubActionsCICD
          aws-region: eu-west-2

      - name: deploy application
        id: ssm
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-0b9792b5c4e0ade4f" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 647932856976.dkr.ecr.eu-west-2.amazonaws.com",
              "docker pull 647932856976.dkr.ecr.eu-west-2.amazonaws.com/cicd-p1:latest",
              "docker stop cicd-p1 || true",
              "docker rm cicd-p1 || true",
              "docker run -d --name cicd-p1 -p 80:3000 647932856976.dkr.ecr.eu-west-2.amazonaws.com/cicd-p1:latest"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"
          echo "command_id=$COMMAND_ID" >> "$GITHUB_OUTPUT"

      - name: wait for command
        run: |
          aws ssm wait command-executed \
            --command-id "${{ steps.ssm.outputs.command_id }}" \
            --instance-id "i-0b9792b5c4e0ade4f"

      - name: get command result
        run: |
          aws ssm get-command-invocation \
            --command-id "${{ steps.ssm.outputs.command_id }}" \
            --instance-id "i-0b9792b5c4e0ade4f"

